add bot first version
RomanOdobesku/llm-recommender pull request #2
Opened 2024-12-09 17:06 UTC by everzakov

2024-12-09 18:36 UTC, RomanOdobesku requested changes
Спасибо за пул реквест! Всё хорошо, есть только пара мелких правок

2024-12-09 18:36 UTC, RomanOdobesku commented on src/bot/main.py
> +from src.logger import LOGGER  # pylint: disable=E0401
Измени плиз коммент для Pylint на pylint: disable=import-error, так более читаемо. Ошибки можно отключать как по коду, так и по названию, Pylint всё пишёт в консоли

2024-12-09 18:36 UTC, RomanOdobesku commented on src/bot/main.py
> +    def save_image(self):
Странная тема, что даже pass нет. Зачем функция сохранения картинки? Если нужна, то напиши реализацию или хотя бы pass

2024-12-09 18:36 UTC, RomanOdobesku commented on src/bot/main.py
> +    """ a simple version of a bandit to get item """
Лучше всё-таки писать объяснение входных и выходных параметров в docstring. Напиши плиз здесь и в других местах. Вот пример:
"""
Retrieves the value associated with the given key using dictionary-like access.

:param key: The key to retrieve the value for.
:return: The value associated with the key.
:raises KeyError: If the key is not in the cache.
"""

2024-12-09 18:36 UTC, RomanOdobesku commented on src/bot/main.py
> +@bot.callback_query_handler(func=lambda call: True)
Добавь плиз сюда ещё функциональность записи фидбека в csv

2024-12-09 18:37 UTC, everzakov commented on src/bot/main.py
> +    def save_image(self):
на pass реагирует линтер :/

2024-12-09 18:43 UTC, RomanOdobesku commented on src/bot/main.py
> +    def save_image(self):
ну лан, тогда так оставим

2024-12-10 10:04 UTC, RomanOdobesku approved these changes
Спасибо, хорошая работа!

2024-12-10 10:05 UTC, merged